<p>
    <a class="btn btn-link btn-xs" href="<?= $this->url('logs'); ?>">Global logs</a>
    <span class="badge ">
        Lifetime <?= $this->deletedLifetime ?>min /<?= $this->buriedLifetime ?>min
    </span>
</p>

<table class="table">
    <tr>
    <th>Id</th>
    <th>Job</th>
    <th>Build</th>
    <th>Status</th>
    <th>Payload</th>
    <th>Created</th>
    <th>Executed</th>
    <th>Finished</th>
    <th>Log</th>
    <th>Restore</th>
    </tr>

    <?php
    /** @var \oat\deploymentsTools\Entity\DeployQueue $entry */

    foreach ($this->entries as $entry) {
        $payload = $entry->getUnserializedJob()->getContent();
        ?>
        <tr class="<?=$entry->getStatusClass()?>" >
            <td><?= $entry->getId(); ?></td>
            <td><?= $entry->getJobName(); ?></td>
            <td><?= isset($payload['buildId'])?$payload['buildId']:''; ?></td>
            <td><?= $entry->getNamedStatus(); ?></td>
            <td>
                <a class="btn btn-default btn-xs" role="button" data-toggle="modal" href="#payload_<?= $entry->getId() ?>"
                   aria-expanded="false" aria-controls="collapseExample">
                    Show
                </a>

                <div class="modal fade" id="payload_<?= $entry->getId() ?>" tabindex="-1" role="dialog"
                     aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">Payload</h4>
                            </div>
                            <div class="modal-body">
                                <?= var_dump($payload); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td><?= $entry->getCreated()->format('d.m.Y H:i:s'); ?></td>
            <td><?= $entry->getExecuted() ? $entry->getExecuted()->format('d.m.Y H:i:s') : '-' ?></td>
            <td><?= $entry->getFinished() ? $entry->getFinished()->format('d.m.Y H:i:s') : '-' ?></td>
            <td><a class="btn-xs btn btn-default" target="_blank"
                   href="<?= $this->url('log', ['file' => isset($payload['buildFolder'])?rawurlencode($payload['buildFolder'] . DIRECTORY_SEPARATOR . 'log' . DIRECTORY_SEPARATOR . 'phing.log'):'']); ?>">Show</a>
            </td>
            <td> <?php if ($entry->isRestorable()) { ?>
                    <a class="btn btn-xs btn-default btn-restore" target="_blank"
                       href="<?= $this->url('restore', ['dir' => rawurlencode($payload['buildFolder'])]) ?>">Restore</a>
                <?php } ?>
            </td>
        </tr>
    <?php } ?>

</table>
<script>
    (function ($) {
        "use strict";

        $('.btn-restore').on('click', function (e) {
            e.preventDefault();
            $.post($(e.target).attr('href'), function () {
                window.location.reload();
            })
        })
    })(jQuery);
</script>